In [1]:
# pandas: robust python package for data analysis and manipulation
# including 2 data structures:
#    - series: labeled array in 1 dimension (only row or column)
#    - dataframe: labeled 2 dimesional data structure (similar to a spread sheet or table)

# DataFrame: a dataframe is comparable to a SQL table or Excel sheet. It features labeled rows and column

In [2]:
import pandas as pd

In [3]:
# read csv file
df = pd.read_csv('MOCK_DATA.csv')

In [6]:
# show firts five rows - muốn show bnhieu dòng thì nhập vào trong ngoặc
df.head()

   id first_name last_name                  email  gender       ip_address
0   1      Henka   Godfree    hgodfree0@skype.com  Female    118.50.85.199
1   2     Leelah   Withrop    lwithrop1@youku.com  Female  208.110.160.243
2   3      Irwin    Ansett  iansett2@illinois.edu    Male   114.253.124.26
3   4       Roda   Bucklee  rbucklee3@mozilla.com  Female   111.10.167.206
4   5  Cherianne     Janas     cjanas4@tripod.com  Female   236.239.167.94

In [10]:
df = pd.read_csv('MOCK_DATA.csv')

In [11]:
df.head()

   id first_name last_name                  email  gender       ip_address
0   1      Henka   Godfree    hgodfree0@skype.com  Female    118.50.85.199
1   2     Leelah   Withrop    lwithrop1@youku.com  Female  208.110.160.243
2   3      Irwin    Ansett  iansett2@illinois.edu    Male   114.253.124.26
3   4       Roda   Bucklee  rbucklee3@mozilla.com  Female   111.10.167.206
4   5  Cherianne     Janas     cjanas4@tripod.com  Female   236.239.167.94

In [12]:
# show 5 bottom rows
df.tail()

,id,first_name,last_name,email,gender,ip_address
995,996,Debra,Pizzey,dpizzeyrn@blog.com,Female,255.166.79.244
996,997,Freddie,Audiss,faudissro@privacy.gov.au,Male,124.45.91.168
997,998,Tracie,Happel,thappelrp@gov.uk,Female,183.94.74.177
998,999,Gabriel,Lingner,glingnerrq@posterous.com,Male,16.117.107.14
999,1000,Georgina,Waith,gwaithrr@arizona.edu,Female,169.227.77.147

In [17]:
# check the shape (numer of rows, number of columns)
df.shape

(1000, 6)

In [15]:
# summarize dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          1000 non-null   int64
 1   first_name  1000 non-null   object
 2   last_name   1000 non-null   object
 3   email       1000 non-null   object
 4   gender      1000 non-null   object
 5   ip_address  1000 non-null   object
dtypes: int64(1), object(5)
memory usage: 47.0+ KB

In [18]:
# statistical summary
df.describe()

                id
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000

In [20]:
# get an exact column
# cú pháp df['tên cột']
df['first_name']

0          Henka
1         Leelah
2          Irwin
3           Roda
4      Cherianne
         ...
995        Debra
996      Freddie
997       Tracie
998      Gabriel
999     Georgina
Name: first_name, Length: 1000, dtype: object

In [21]:
df['email']

0           hgodfree0@skype.com
1           lwithrop1@youku.com
2         iansett2@illinois.edu
3         rbucklee3@mozilla.com
4            cjanas4@tripod.com
                 ...
995          dpizzeyrn@blog.com
996    faudissro@privacy.gov.au
997            thappelrp@gov.uk
998    glingnerrq@posterous.com
999        gwaithrr@arizona.edu
Name: email, Length: 1000, dtype: object

In [26]:
# get multiple columns
# cú pháp df[['col1', 'col2']]
df[['last_name', 'gender', 'first_name', 'email']] # phải có hai ngoặc vuông

    last_name  gender first_name                     email
0     Godfree  Female      Henka       hgodfree0@skype.com
1     Withrop  Female     Leelah       lwithrop1@youku.com
2      Ansett    Male      Irwin     iansett2@illinois.edu
3     Bucklee  Female       Roda     rbucklee3@mozilla.com
4       Janas  Female  Cherianne        cjanas4@tripod.com
..        ...     ...        ...                       ...
995    Pizzey  Female      Debra        dpizzeyrn@blog.com
996    Audiss    Male    Freddie  faudissro@privacy.gov.au
997    Happel  Female     Tracie          thappelrp@gov.uk
998   Lingner    Male    Gabriel  glingnerrq@posterous.com
999     Waith  Female   Georgina      gwaithrr@arizona.edu

[1000 rows x 4 columns]

In [28]:
# rowing by index - get a row
df.iloc[1]

id                              2
first_name                 Leelah
last_name                 Withrop
email         lwithrop1@youku.com
gender                     Female
ip_address        208.110.160.243
Name: 1, dtype: object

In [29]:
# labeled based
df.loc[0]

id                              1
first_name                  Henka
last_name                 Godfree
email         hgodfree0@skype.com
gender                     Female
ip_address          118.50.85.199
Name: 0, dtype: object

In [43]:
# filtering rows
# lọc các dòng với điều kiện
df[(df['id'] > 900)]

,id,first_name,last_name,email,gender,ip_address
900,901,Jeffrey,Marriage,jmarriagep0@over-blog.com,Male,34.191.150.135
901,902,Barbee,Vreiberg,bvreibergp1@pbs.org,Female,9.34.117.73
902,903,Riobard,Fairchild,rfairchildp2@bbb.org,Male,116.44.113.69
903,904,Dorotea,Whettleton,dwhettletonp3@washingtonpost.com,Female,189.77.250.76
904,905,Marcella,Baress,mbaressp4@hatena.ne.jp,Non-binary,237.214.79.33
...,...,...,...,...,...,...
995,996,Debra,Pizzey,dpizzeyrn@blog.com,Female,255.166.79.244
996,997,Freddie,Audiss,faudissro@privacy.gov.au,Male,124.45.91.168
997,998,Tracie,Happel,thappelrp@gov.uk,Female,183.94.74.177
998,999,Gabriel,Lingner,glingnerrq@posterous.com,Male,16.117.107.14
999,1000,Georgina,Waith,gwaithrr@arizona.edu,Female,169.227.77.147

In [34]:
# multiple conditions
# mỗi điều kiện trong 1 ngoặc đơn
df[(df['id'] > 900) & (df['gender'] == 'Female')]

,id,first_name,last_name,email,gender,ip_address
901,902,Barbee,Vreiberg,bvreibergp1@pbs.org,Female,9.34.117.73
903,904,Dorotea,Whettleton,dwhettletonp3@washingtonpost.com,Female,189.77.250.76
906,907,Phyllys,Christmas,pchristmasp6@prweb.com,Female,28.237.218.77
907,908,Del,McRavey,dmcraveyp7@msu.edu,Female,216.24.254.16
909,910,Ruthi,Sabben,rsabbenp9@google.co.jp,Female,81.120.151.86
910,911,Annaliese,Shobrook,ashobrookpa@fotki.com,Female,151.21.47.134
916,917,Brenda,Lintall,blintallpg@ustream.tv,Female,126.253.2.215
918,919,Dodie,Ruddle,druddlepi@smh.com.au,Female,233.24.67.87
919,920,Arabelle,Pedden,apeddenpj@cam.ac.uk,Female,117.240.37.209
920,921,Esmaria,Leitche,eleitchepk@facebook.com,Female,42.255.38.62
923,924,Kelli,Crombie,kcrombiepn@alibaba.com,Female,164.162.25.122
927,928,Courtenay,Hanford,chanfordpr@google.cn,Female,149.219.199.126
930,931,Selena,Reaper,sreaperpu@home.pl,Female,94.56.36.46
932,933,Donnamarie,Bedberry,dbedberrypw@constantcontact.com,Female,28.155.209.24
933,934,Florella,Oldman,foldmanpx@multiply.com,Female,139.146.251.103
939,940,Peta,Matzke,pmatzkeq3@gnu.org,Female,66.5.226.58
940,941,Amalee,MacRorie,amacrorieq4@a8.net,Female,247.97.253.36
944,945,Charlene,Purdie,cpurdieq8@squidoo.com,Female,54.204.174.190
945,946,Bonni,Dungate,bdungateq9@constantcontact.com,Female,81.232.170.144
948,949,Hortense,O'Kielt,hokieltqc@nsw.gov.au,Female,77.113.177.245
950,951,Ethyl,Benedikt,ebenediktqe@dell.com,Female,222.9.6.89
951,952,Darcy,Nunnery,dnunneryqf@scribd.com,Female,240.170.100.144
953,954,Issy,Baudin,ibaudinqh@dot.gov,Female,239.220.118.88
954,955,Shawn,Voase,svoaseqi@unicef.org,Female,168.32.131.173
956,957,Josi,Upchurch,jupchurchqk@fastcompany.com,Female,130.22.92.170
958,959,Petronille,Dowgill,pdowgillqm@discovery.com,Female,99.230.206.230
959,960,Bernice,Peppett,bpeppettqn@netscape.com,Female,82.49.96.113
961,962,Diann,D'Cruze,ddcruzeqp@comcast.net,Female,114.112.24.207
963,964,Yolanda,Delf,ydelfqr@delicious.com,Female,224.91.255.162
964,965,Caitrin,Hallwell,challwellqs@ocn.ne.jp,Female,52.120.217.150
968,969,Ginnifer,Collicott,gcollicottqw@mayoclinic.com,Female,155.129.70.213
972,973,Sophia,Macura,smacurar0@constantcontact.com,Female,166.206.36.91
973,974,Scarlett,Clemencet,sclemencetr1@china.com.cn,Female,135.184.173.166
974,975,Merrili,Couvet,mcouvetr2@hp.com,Female,162.116.127.164
975,976,Lurline,Meldon,lmeldonr3@tamu.edu,Female,232.233.128.7
977,978,Genevra,Uccello,guccellor5@vimeo.com,Female,210.30.79.249
978,979,Desiri,Privett,dprivettr6@wikimedia.org,Female,175.28.135.222
980,981,Naomi,McQueen,nmcqueenr8@globo.com,Female,212.200.115.20
982,983,Whitney,Iwanczyk,wiwanczykra@dot.gov,Female,200.180.194.56
983,984,Florencia,Body,fbodyrb@list-manage.com,Female,97.163.247.104
984,985,Peg,Brearty,pbreartyrc@instagram.com,Female,255.216.4.6
986,987,Malia,Kempster,mkempsterre@twitpic.com,Female,112.153.113.47
987,988,Sophie,Drinnan,sdrinnanrf@redcross.org,Female,26.251.90.106
989,990,Olympie,Pallin,opallinrh@guardian.co.uk,Female,149.115.221.247
990,991,Lind,Antoinet,lantoinetri@comsenz.com,Female,236.95.9.215
991,992,Carin,Tanswill,ctanswillrj@tamu.edu,Female,61.205.116.229
992,993,Domeniga,Geratt,dgerattrk@macromedia.com,Female,222.37.94.142
993,994,Mariellen,Snailham,msnailhamrl@privacy.gov.au,Female,121.16.151.149
995,996,Debra,Pizzey,dpizzeyrn@blog.com,Female,255.166.79.244
997,998,Tracie,Happel,thappelrp@gov.uk,Female,183.94.74.177
999,1000,Georgina,Waith,gwaithrr@arizona.edu,Female,169.227.77.147

In [35]:
# modify columns - create new col
df['NewCol'] = df['id'] + 2

In [36]:
df['id'] = df['id'] * 2

In [ ]:
# drop a column - xóa biến
# xóa cột axis = 1
df.drop('first_name', axis=1, inplace = True)

In [37]:
# drop a row
# xóa dòng axis = 0
df.drop(0, axis = 0, inplace = True)

In [38]:
df.head()

,id,first_name,last_name,email,gender,ip_address,NewCol
1,4,Leelah,Withrop,lwithrop1@youku.com,Female,208.110.160.243,4
2,6,Irwin,Ansett,iansett2@illinois.edu,Male,114.253.124.26,5
3,8,Roda,Bucklee,rbucklee3@mozilla.com,Female,111.10.167.206,6
4,10,Cherianne,Janas,cjanas4@tripod.com,Female,236.239.167.94,7
5,12,Marvin,Jeanenet,mjeanenet5@google.it,Male,248.139.182.149,8

In [39]:
# read csv file again
df = pd.read_csv('MOCK_DATA.csv')

In [40]:
df.head()

   id first_name last_name                  email  gender       ip_address
0   1      Henka   Godfree    hgodfree0@skype.com  Female    118.50.85.199
1   2     Leelah   Withrop    lwithrop1@youku.com  Female  208.110.160.243
2   3      Irwin    Ansett  iansett2@illinois.edu    Male   114.253.124.26
3   4       Roda   Bucklee  rbucklee3@mozilla.com  Female   111.10.167.206
4   5  Cherianne     Janas     cjanas4@tripod.com  Female   236.239.167.94

In [42]:
# sort values
df.sort_values('gender', ascending = True)

,id,first_name,last_name,email,gender,ip_address
399,400,Ewan,Dorber,edorberb3@aboutads.info,Agender,131.206.197.149
739,740,Dunstan,Playden,dplaydenkj@slashdot.org,Agender,151.234.11.133
704,705,Pooh,Charer,pcharerjk@google.com,Agender,106.74.96.27
764,765,Simone,Scowen,sscowenl8@hp.com,Agender,239.8.194.171
947,948,Magdalen,Dilloway,mdillowayqb@dyndns.org,Agender,105.24.196.95
...,...,...,...,...,...,...
895,896,Christyna,Clampton,cclamptonov@mlb.com,Polygender,191.30.128.43
580,581,Trude,Batchellor,tbatchellorg4@printfriendly.com,Polygender,96.225.171.85
836,837,Nadia,Carl,ncarln8@rambler.ru,Polygender,187.5.237.82
164,165,Kaspar,Deaton,kdeaton4k@mysql.com,Polygender,58.183.251.210
43,44,Leland,Duddell,lduddell17@mozilla.org,Polygender,62.174.78.208

In [44]:
# check & handle missing data

In [45]:
# check for null values
# True → ô bị thiếu (NaN)
# False → ô có dữ liệu
df.isnull().sum()

id            0
first_name    0
last_name     0
email         0
gender        0
ip_address    0
dtype: int64

In [46]:
# xóa các dòng có giá trị bị thiếu - xóa quan sát
df.dropna(inplace = True) # True là các dòng chứa giá trị bị thiếu phía trên

In [47]:
# fil data in missing values
df.fillna(0, inplace = True) # thay thế các giá trị null = 0

In [48]:
# export to csv
df.to_csv('output.csv', index = False) # index = False là không ghi cột index ra file csv còn true là sẽ có thêm cột index